name: miniproject_258727X
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pandas>=1.5.0
  - numpy>=1.24.0
  - matplotlib>=3.6.0
  - seaborn>=0.12.0
  - plotly>=5.10.0
  - scikit-learn>=1.2.0
  - jupyter>=1.0.0
  - ipykernel>=6.0.0
  - pip
  - pip:
    - kaleido>=0.2.0
